### ISSUE TITLE
update Gate for React 18

### ISSUE THREAD

**Issue by EliseyMartynov** [effector/effector#803] opened 2022-10-11 09:06 UTC
## Proposal

Change API of Gate, so it could work with React 18 in a proper way. Since React 18, in StrictMode (development only) - all components are re-mounting once - they made this to prepare developers and our projects to breaking change of preserving state.
But Gate should work like it always worked without any unexpected things.
For now Gate produces x2 events since new `useEffect` behavior (at least being faced with `.open`). That's sad.

## Use case

Just make it working like it works with React <18.

**Comment by sergeysova** [comment] 2022-10-11 09:52
🤔

**Comment by igorkamyshev** [comment] 2022-12-15 10:31
I assume it is a duplicate of #804

**Closed by igorkamyshev** 2022-12-15 10:31 UTC
Labels: duplicate, RFC
