### ISSUE TITLE
`allSettled` doesn't support `$store` as argument silently 

### ISSUE THREAD

**Issue by igorkamyshev** [effector/effector#608] opened 2022-01-26 12:51 UTC
**What is the current behavior:**

If we provide any store to `allSettled` it will change it's value, but later `serialize` won't detect it.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**

https://share.effector.dev/wcQz3AOQ

**What is the expected behavior:**

Throw exception on passing store to `allSettled` or fully support it.

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**

`master`

**Comment by sergeysova** [comment] 2022-02-06 17:21
@igorkamyshev It will be released in the next patch release.

**Comment by AlexandrHoroshih** [comment] 2022-02-06 18:33
In current master `allSettled` now throws error, that stores are forbidden in allSettled - but should it be this way? 🤔

**Comment by AlexandrHoroshih** [comment] 2022-02-06 18:35
Also, this problem affects only serializing of store state. Other cases with store in allSettled are working correctly - e.g. tests, which can be even noticed in original reproduce

```ts
const viewer = createDomain()

const $is = createStore(false)

const scope = fork()

await allSettled($is, {scope, params: true})

console.log('ON SCOPE', scope.getState($is)) // `true`, as expected
```

**Comment by AlexandrHoroshih** [comment] 2022-02-06 18:36
So, looks like forbidding stores in allSettled is a change with a large blast radius and should be deperecated with a warning first 🤔

**Closed** 2022-02-06 20:29 UTC
Labels: bug, discussion, fork api
