### ISSUE TITLE
Update imports in effector-vue

### ISSUE THREAD

**Issue by zerobias** [effector/effector#919] opened 2023-06-18 13:51 UTC
Need to replace imports in source code from `import Vue from "vue"` to `import * as Vue from "vue"`

**Comment by igorkamyshev** [comment] 2023-11-03 08:42
1. Webpack in Vue ecosystem is deprecated — https://cli.vuejs.org/guide/webpack.html
2. For new projects, Vite is recommended — https://github.com/vuejs/create-vue, I use Vite + `effector-vue/composition` in https://github.com/igorkamyshev/withease/blob/master/apps/website/docs/web-api/page_visibility.live.vue, it has no errors.

I suggest closing this issue because I have no idea how to reproduce it and why it exists 🫠

**Comment by igorkamyshev** [comment] 2023-11-03 09:08
I've checked it in Webpack-based project — https://github.com/igorkamyshev/vue-imports-effector/blob/main/src/Hello.vue, it works great. So, let's close it for now.

**Closed by igorkamyshev** 2023-11-03 09:08 UTC
Labels: bug, effector-vue
