### ISSUE TITLE
Typings of useEvent are incorrect

### ISSUE THREAD

**Issue by alatielle** [effector/effector#500] opened 2021-06-22 14:18 UTC
## Missing/Incorrect APIs

The result of `someDomain.createEvent()` is assignable to `() => void`, but `useEvent(event)` is not:
```
TS2322: Type '(payload: void) => void' is not assignable to type '() => void'.
```

**Comment by zerobias** [comment] 2021-06-26 20:13
Fixed in `effector-react 21.3.3`

**Comment by igorkamyshev** [comment] 2022-07-15 04:41
I've found out that this issue exists in `useUnit`, so let me reopen it.

**Comment by sergeysova** [comment] 2022-07-17 13:39
@igorkamyshev Can you reproduce this issue and create a new one with correct title?

(Because, I can't reproduce https://tsplay.dev/WyePbW)

**Comment by igorkamyshev** [comment] 2022-07-18 05:44
Sure

**Closed by igorkamyshev** 2022-07-18 05:44 UTC
Labels: typings, effector-react, effector-react/scope
