### ISSUE TITLE
`effector/babel-plugin` plugin doesn't process `factories` field

### ISSUE THREAD

**Issue by rushelex** [effector/effector#732] opened 2022-06-23 16:21 UTC
**What is the current behavior:**
If you add the `factories` field in the `effector/babel-plugin` configuration and specify the actual path of the factory that is imported into the model files, then the `sid` for units is specified without additionally specifying the `sid` of the factory.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar:**
https://stackblitz.com/edit/effector-react-1eg5yl?file=src%2Fmodel.ts

**What is the expected behavior:**
The `factories` field is handled correctly and the `sid` of the units created by the factory is different.

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**
OS: any
Browser: any

> _Did this work in previous versions of effector?_

I don't know.

**Comment by Drevoed** [comment] 2022-07-17 20:22
Factories field must point to the factory path relative to ***root*** folder.

So in your case it is fixed by setting factories like this:
```ts
{
  factories: ['./src/shared/lib/effector/store']
}
```

**Comment by rushelex** [comment] 2022-07-18 08:06
> So in your case it is fixed by setting factories like this:

No, it doesn't work. In addition, they wrote in the telegram chat that the path should be exactly the same as that written in the import construct.

**Comment by sergeysova** [comment] 2022-07-18 08:16
Write full path from the root into the `factories`:

https://stackblitz.com/edit/effector-react-otbbgz?file=.babelrc

```diff
-"factories": ['./shared/lib/effector/store'],
+"factories": ["./src/shared/lib/effector/store"]
```

Also, I removed `babel` option from `react()` plugin in `vite.config.js`. Prefer to use `babel()` with `extensions` list

**Closed** 2022-07-18 08:17 UTC
Labels: bug

**Comment by rushelex** [comment] 2022-07-18 08:22
But that doesn't solve the problem...

Look at [this code](https://stackblitz.com/edit/effector-react-otbbgz?file=src%2Fmodel.ts). There are comments "It works" and "It doesn't work". That is the meaning of this issue. The factory code doesn't work properly even if there are different sids.

**Comment by rushelex** [comment] 2022-07-18 08:27
https://user-images.githubusercontent.com/41122157/179472713-d70b2130-332c-423a-8b4b-1676de5759de.mp4

**Comment by sergeysova** [comment] 2022-07-18 08:33
Oh, in the code/isse wasn't comment of the expected behaviour.

**Comment by sergeysova** [comment] 2022-07-18 08:34
Because the sids is different, you need to search problem in your fabric implementation, not in the babel-plugin.

**Comment by sergeysova** [comment] 2022-07-18 08:35
You made CATASTROPHIC hard code and made a bug inside it:

```diff

const getIntersectingEvents = <
  TargetStore extends Store<any>,
  EventMap extends Array<[TargetStore, Event<void>]>
>(
  targetStore: TargetStore,
  eventMap: EventMap
): Event<void>[] => {
  return eventMap
-    .filter(([store]) => store.shortName !== targetStore.shortName)
+    .filter(([store]) => store.sid !== targetStore.sid)
    .map(toEvent);
};
```

**Comment by sergeysova** [comment] 2022-07-18 08:36
I totally recommend to rewrite this code without using `.sid` or `.shortName`.

**Comment by sergeysova** [comment] 2022-07-18 08:44
Previous code works well because it really had different shortNames. But stores create inside a fabric will have the same name, because inside the fabric function variable has the same name for the each fabric instance, there is only changes the name **after** fabric call.

```ts
const $a = createStore(0); // .shortName = $a
const $b = createStore(1); // .shortName = $b
```

```ts
function factory() {
  const $demo = createStore(0)
  return $demo;
}

const $a = factory(); // .shortName = $demo
const $b = factory(); // .shortName = $demo
```

That's why you don't need to write code that depends on these internal properties. It is really fragile way to write code
