### ISSUE TITLE
Guard samples stale data from combined store

### ISSUE THREAD

**Issue by alpatovdanila** [effector/effector#544] opened 2021-10-28 15:59 UTC
**What is the current behavior:**
Guard passes stale data from combined store to effect. 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**
https://share.effector.dev/jSQ3WPPg

**What is the expected behavior:**
I am expecting actual state of $requestData store to be passed to target effect

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**
Bug occurs on 22.1.2 version of Effector

**Comment by MichaelShipitsyn** [comment] 2021-10-31 11:56
It seems that the problem is not in guard. I think the problem is in calculation priority of the clock fn parameter in sample - https://share.effector.dev/MtzNQ2Gx

**Comment by zerobias** [comment] 2021-10-31 12:54
@MichaelShipitsyn yes, you right

The more I think about it, the more issues I find. The main question is whether the clock without source should have the same priority as the source in the usual case?

**Comment by AlexandrHoroshih** [comment] 2021-10-31 16:28
Weird enough, but wrapping clock in sample into another sample solves the issue 🤔
And making that sample wrapper greedy recreates the bug: https://share.effector.dev/mc4cQ01f

So isn't the problem actually in `sample`'s clock batching mechanism? Looks like, in this situation, sample takes first triggered value of the clock instead of the last one

Another question i see is why there are two `combine`-ed store update calls? 
First of those calls is the one with stale data, but i would expect only one call there 🤔

Changing that first sample to greedy one ([here](https://share.effector.dev/77y1T1tK)) or changing it to basic `.on` ([there](https://share.effector.dev/clerqich)) fixes the issue because there is only one update of combined store - without any stale data 🤔

**Comment by zerobias** [comment] 2021-11-02 03:52
@AlexandrHoroshih big thanks for deep investigation, I found an issue using your examples 👍 

Yes, the bug was in implementation of sample: in case with source store, the first value of clock was used instead of last one

I will publish a fix during this week

**Comment by zerobias** [comment] 2021-11-02 03:55
And as for multiple combine updates - it happens because $filterValues is updated strictly after $selectedCities → $requestData update chain. Look at [ordering snapshots](https://github.com/effector/effector/blob/3b2a9bb60edc4521374a9ea5660e2010e088f5b3/src/effector/__tests__/sample/order.test.ts#L171)

**Comment by AlexandrHoroshih** [comment] 2021-11-02 06:21
Always glad to help 🤘

>  it happens because $filterValues is updated strictly after $selectedCities → $requestData update chain

Yes, i see that, but isn't this an observable glitchy value?

In those examples both dependencies of combined store are changed in the same computation cycle, so i would expect that combine will be updated (or at least call its watchers) only once during this cycle, without calling it on stale data 🤔

I see that this has something to do with sample priority level in this case, because by raising the priority manually (via `greedy: true` or using `.on` instead) we can no longer observe that stale value 🤔

**Comment by doasync** [comment] 2021-11-11 13:38
> I will publish a fix during this week

@zerobias How's it going with the fix?

**Comment by zerobias** [comment] 2021-11-24 16:23
@doasync I merged the release of this fix with a few others updates, will be released in an upcoming minor release as soon as I figure out the [types for the sample](https://github.com/effector/effector/commit/c58c9aea71031e582f569aac2fe2fe8b2087203c)

**Closed** 2021-12-08 15:01 UTC
Labels: bug, core
